version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: rlhf-postgres
    environment:
      POSTGRES_DB: rlhf_db
      POSTGRES_USER: rlhf_user
      POSTGRES_PASSWORD: rlhf_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rlhf-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rlhf-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rlhf-network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rlhf-backend
    environment:
      - DATABASE_URL=postgresql://rlhf_user:rlhf_password@postgres:5432/rlhf_db
      - REDIS_URL=redis://redis:6379
      - MODEL_STORAGE_PATH=/app/models
      - UPLOAD_DIR=/app/uploads
    volumes:
      - model_storage:/app/models
      - upload_storage:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - rlhf-network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rlhf-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rlhf-network
    restart: unless-stopped

  # Celery Worker for Background Tasks
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rlhf-celery-worker
    environment:
      - DATABASE_URL=postgresql://rlhf_user:rlhf_password@postgres:5432/rlhf_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - model_storage:/app/models
      - upload_storage:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - rlhf-network
    restart: unless-stopped
    command: celery -A app.core.celery worker --loglevel=info

  # Celery Beat for Scheduled Tasks
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rlhf-celery-beat
    environment:
      - DATABASE_URL=postgresql://rlhf_user:rlhf_password@postgres:5432/rlhf_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - rlhf-network
    restart: unless-stopped
    command: celery -A app.core.celery beat --loglevel=info

  # Flower for Celery Monitoring
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rlhf-flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - rlhf-network
    restart: unless-stopped
    command: celery -A app.core.celery flower --port=5555

volumes:
  postgres_data:
  redis_data:
  model_storage:
  upload_storage:

networks:
  rlhf-network:
    driver: bridge 